"""update routine and feedback fields

Revision ID: c78c19e1d998
Revises: e1d172a550f2
Create Date: 2026-05-29 23:33:11.033991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c78c19e1d998'
down_revision: Union[str, Sequence[str], None] = 'e1d172a550f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('coach_profiles', 'name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=40),
               existing_nullable=False)
    op.alter_column('coach_profiles', 'style',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=80),
               existing_nullable=False)
    op.add_column('feedbacks', sa.Column('period_start', sa.Date(), nullable=False))
    op.add_column('feedbacks', sa.Column('period_end', sa.Date(), nullable=False))
    op.alter_column('goals', 'title',
               existing_type=sa.VARCHAR(length=150),
               type_=sa.String(length=60),
               existing_nullable=False)
    op.drop_column('habit_logs', 'note')
    op.drop_column('habit_logs', 'completed_count')
    op.add_column('habits', sa.Column('duration_minutes', sa.Integer(), nullable=False))
    op.add_column('habits', sa.Column('recurrence_rule', sa.Text(), nullable=False))
    op.add_column('habits', sa.Column('start_date', sa.Date(), nullable=False))
    op.drop_column('habits', 'target_unit')
    op.drop_column('habits', 'target_count')
    op.drop_column('habits', 'frequency_type')
    op.drop_column('routine_item_logs', 'note')
    op.add_column('routine_items', sa.Column('schedule_type', sa.String(length=30), nullable=False))
    op.add_column('routine_items', sa.Column('start_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('routine_items', sa.Column('end_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('routine_items', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('routine_items', 'scheduled_time')
    op.drop_column('routine_items', 'priority')
    op.add_column('users', sa.Column('language', sa.String(length=10), nullable=False))
    op.drop_column('users', 'locale')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.drop_column('users', 'language')
    op.add_column('routine_items', sa.Column('priority', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('routine_items', sa.Column('scheduled_time', postgresql.TIME(), autoincrement=False, nullable=True))
    op.alter_column('routine_items', 'duration_minutes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('routine_items', 'end_at')
    op.drop_column('routine_items', 'start_at')
    op.drop_column('routine_items', 'schedule_type')
    op.add_column('routine_item_logs', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('habits', sa.Column('frequency_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('habits', sa.Column('target_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('habits', sa.Column('target_unit', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.drop_column('habits', 'start_date')
    op.drop_column('habits', 'recurrence_rule')
    op.drop_column('habits', 'duration_minutes')
    op.add_column('habit_logs', sa.Column('completed_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('habit_logs', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('goals', 'title',
               existing_type=sa.String(length=60),
               type_=sa.VARCHAR(length=150),
               existing_nullable=False)
    op.drop_column('feedbacks', 'period_end')
    op.drop_column('feedbacks', 'period_start')
    op.alter_column('coach_profiles', 'style',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('coach_profiles', 'name',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
    # ### end Alembic commands ###
