"""add signature plan to users

Revision ID: ea2f5253c17c
Revises: c78c19e1d998
Create Date: 2026-06-01 14:13:54.692481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2f5253c17c'
down_revision: Union[str, Sequence[str], None] = 'c78c19e1d998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('signature_plan', sa.String(length=30), nullable=False))
    op.alter_column('users', 'language',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'language',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    op.drop_column('users', 'signature_plan')
    # ### end Alembic commands ###
